name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # TODO include windows-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: sudo apt-get install -y clang-format clang-tidy clang-tools
      - name: Check File Headers
        run: python3 ./scripts/check_copyright_notice.py
      - name: CMake configuration
        run: |
          mkdir build && cd build
          cmake ..
      - name: Check clang-format
        run: ./scripts/check-clang-format.sh
      - name: Check clang-tidy
        run: ./scripts/check-clang-tidy.sh
      - name: Build
        run: |
          cd build
          make
      - name: Run tests
        run: |
          ./build/lib/test/LydiaLibTest