name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]  # TODO include macos-latest, windows-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -f clang-format-9 clang-tidy-9
          sudo apt-get install -f gcov gcovr
      - name: Check File Headers
        run: python3 ./scripts/check_copyright_notice.py
      - name: Configure CMake
        run: |
          ./scripts/_configure-cmake-ci.sh .
      - name: Check clang-format
        run: ./scripts/check-clang-format.sh
      - name: Check clang-tidy
        run: ./scripts/check-clang-tidy.sh
      - name: Build
        run: |
          cd build && make -j
      - name: Test
        run: |
          ./scripts/_test-cmake-ci.sh
