name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]  # TODO include windows-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build
        run: |
          mkdir build && cd build
          cmake ..
          make
      - name: Run tests
        run: |
          ./build/lib/test/LydiaLibTest