name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  lint:
    runs-on: [ubuntu-latest]
    - name: Install dependencies
      run: |
        sudo apt-get install -y clang-format-9
    - name: Check File Headers
      run: python3 ./scripts/check_copyright_notice.py
    - name: Check clang-format
      run: ./scripts/check-clang-format.sh

  run:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]  # TODO include macos-latest, windows-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-9
          sudo apt-get install -y wget

          # install flex/bison
          sudo apt-get install -y flex
          sudo apt-get install -y bison

          sudo apt-get install -y libgraphviz-dev
          sudo python -m pip install gcovr
      - name: Install CUDD
        run: |
          wget https://github.com/whitemech/cudd/releases/download/v3.0.0/cudd_3.0.0_linux-amd64.tar.gz
          tar -xf cudd_3.0.0_linux-amd64.tar.gz
          cd cudd_3.0.0_linux-amd64
          sudo cp -P lib/* /usr/local/lib/
          sudo cp -Pr include/* /usr/local/include
      - name: Install MONA
        run: |
          wget https://github.com/whitemech/MONA/releases/download/v1.4-18.dev0/mona_1.4-18.dev0_linux-amd64.tar.gz
          tar -xf mona_1.4-18.dev0_linux-amd64.tar.gz
          cd mona_1.4-18.dev0_linux-amd64
          sudo cp -P lib/* /usr/local/lib/
          sudo cp -Pr include/* /usr/local/include
      - name: Install MiniSAT
        run: |
          wget https://github.com/whitemech/minisat/releases/download/v2.1.0/minisat_2.1.0_linux-amd64.tar.gz
          tar -xf minisat_2.1.0_linux-amd64.tar.gz
          cd minisat_2.1.0_linux-amd64
          sudo cp -P lib/* /usr/local/lib/
          sudo cp -Pr include/* /usr/local/include
      - name: Check clang-tidy
        run: ./scripts/check-clang-tidy.sh
      - name: Configure CMake
        run: ./scripts/_ci-configure.sh
      - name: Build
        run: cd build && make test -j
      - name: Test
        run: ./scripts/_ci-test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
