name: Lydia CI pipeline

on:
  push:
    branches:
      - develop
      - master
  pull_request:

jobs:
  lint:
    runs-on: [ubuntu-latest]
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install dependencies
      run: |
        sudo apt-get install -y clang-format-9
    - name: Check File Headers
      run: python3 ./scripts/check_copyright_notice.py
    - name: Check clang-format
      run: ./scripts/check-clang-format.sh

  test:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]  # TODO include macos-latest, windows-latest

    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-tidy-9
          sudo apt-get install -y wget

          # install flex/bison
          sudo apt-get purge -y flex
          sudo apt-get purge -y bison
          sudo apt-get install -y flex bison
          sudo apt-get autoremove

          sudo apt-get install -y libgraphviz-dev
          sudo python -m pip install gcovr
      - name: Install dependencies
        run: ./scripts/_ci-install-dependencies-ubuntu.sh
      - name: Check clang-tidy
        run: ./scripts/check-clang-tidy.sh
      - name: Configure CMake
        run: ./scripts/_ci-configure.sh
      - name: Build
        run: |
          cd build
          cat compile_commands.json
          VERBOSE=1 make lydiaTest -j
      - name: Test
        run: ./scripts/_ci-test.sh
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          yml: ./codecov.yml
          fail_ci_if_error: true
